### ISSUE TITLE
Sapphire armor causes a crash.

### ISSUE THREAD

**Issue by CallMeEchoCodes** [TriQue06/mythic-upgrades-1.20.x#62] opened 2023-11-13 07:05 UTC
Hi! I am currently debugging a server crash that occurs when using Sapphire armor. I had a look at the code but i can't see any issues. The server uses the origins mod which may be related.

[crash-2023-11-12_22.30.02-server.txt](https://github.com/TriQue06/mythic-upgrades-1.20.x/files/13331571/crash-2023-11-12_22.30.02-server.txt)

**Comment by CyberSteve777** [comment] 2023-11-25 15:58
@CallMeEchoCodes Can you provide more info pls. What race were your player and were you doing before crash appeared?

**Comment by CallMeEchoCodes** [comment] 2023-11-27 00:17
@CyberSteve777 Hi! I was playing as Truffle (a custom origin) and the player i killed was a Bee (another custom origin). However this bug appears to happen as any origin to many mobs. I have experienced it in an Enderman farm i made and my origin doesn't modify anything related to potion effects or deflection.

**Comment by CallMeEchoCodes** [comment] 2023-11-27 00:20
Just realised i really didn't provide that much context here:
1. This seems to occur when killing something while wearing the armor. The only pattern i have found is that anything with more or less than a vanilla players health causes it more.
2. The crash specifically mentions the Mixins on the Player, which would seem to imply this bug is in one of those files.
3.  My running theory has been that the non standard health is causing a division by 0 somewhere, causing a crash. Java isn't a language I'm great at so this is probably wrong but ig its a starting point.

**Comment by CyberSteve777** [comment] 2023-11-27 22:45
@CallMeEchoCodes actually, looking at crash report, it seems that's the problem is in infinite recursion, where some part of code just calls itself infinetly. I think it's bc techincally you can deflect damage to yourself caused by you. I hope this is the cause, which I'll fix

**Comment by TriQue06** [comment] 2024-01-20 22:10
This issue has been fixed with Update 2.4.0.

**Closed by TriQue06** 2024-01-20 22:10 UTC
