### ISSUE TITLE
Incompatability with mod "AdventureZ"

### ISSUE THREAD

**Issue by cobaltlol** [TriQue06/mythic-upgrades-1.20.x#45] opened 2023-10-15 19:07 UTC
https://pastebin.com/6ydSH8Ry - latest.log, having both AdventureZ or Mythic upgrades crashes the game upon starting but stops crashing when either are removed.

**Comment by solonovamax** [comment] 2023-10-16 16:06
This regression was introduced `2.3.0`, and also exists in `2.3.1`.

I believe the issue was introduced by 363bd907a2c29523dc68948191599a29f1126e71 or by d8db20aac6f3b46ad013ee711651fc725eeb4dbb. (though this may be an incorrect assumption) However, since that mixin is only injecting into the HEAD of the method and not overwriting it completely, I believe the compatibility issue may be on their end.

See: Globox1997/AdventureZ#161

**Comment by solonovamax** [comment] 2023-10-16 16:23
Do note: I *may* be incorrect in that assessment that it's an issue with adventurez.

**Comment by CyberSteve777** [comment] 2023-10-16 19:06
Hello! Yes, it was issue on our side, fixed in #47

**Comment by CyberSteve777** [comment] 2023-10-16 19:37
@solonovamax Previously I was overriding `PlayerEntity.damage()` method, however, I could just mixin here. Now I have done it. Tested in dev environment with latest 1.20.1 AdventureZ, no longer receiving crashes

**Comment by cobaltlol** [comment] 2023-10-16 19:39
good to know

**Comment by solonovamax** [comment] 2023-10-16 20:07
> @solonovamax Previously I was overriding `PlayerEntity.damage()` method, however, I could just mixin here. Now I have done it. Tested in dev environment with latest 1.20.1 AdventureZ, no longer receiving crashes

Alright, when you publish a new release, I'll give it a test myself (too lazy to build from source rn lol)

**Comment by CyberSteve777** [comment] 2023-10-27 18:02
@solonovamax 2.3.2 published, feel free to test :D

**Comment by TriQue06** [comment] 2023-10-27 18:14
fixed

**Closed by TriQue06** 2023-10-27 18:14 UTC
